"""update post2

Revision ID: 1497d90e78bd
Revises: e5cfa8291b77
Create Date: 2018-03-25 18:22:13.001758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1497d90e78bd'
down_revision = 'e5cfa8291b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('res_posts', sa.Column('post_body_md', sa.Text(), nullable=True))
    op.drop_column('res_posts', 'post_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('res_posts', sa.Column('post_body', mysql.TEXT(), nullable=True))
    op.drop_column('res_posts', 'post_body_md')
    # ### end Alembic commands ###
