"""add file

Revision ID: 38b61b9a4c02
Revises: 48eff7641cc4
Create Date: 2018-03-24 17:56:09.000471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38b61b9a4c02'
down_revision = '48eff7641cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('res_files', sa.Column('file_isextern', sa.Boolean(), nullable=False))
    op.add_column('res_files', sa.Column('file_uri', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('res_files', 'file_uri')
    op.drop_column('res_files', 'file_isextern')
    # ### end Alembic commands ###
