"""add child class for res_postclass & add ref to res_post

Revision ID: 8809cee72991
Revises: a5e7ce8a9f24
Create Date: 2018-10-18 12:59:29.892754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8809cee72991'
down_revision = 'a5e7ce8a9f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'res_files', 'ua_users', ['file_uid'], ['ua_user_id'])
    op.add_column('res_postclasses', sa.Column('postclass_pid', sa.Integer(), nullable=True))
    #op.alter_column('res_postclasses', 'postclass_uid', existing_type=mysql.INTEGER(display_width=11), nullable=True)
    # op.create_foreign_key(None, 'res_postclasses', 'ua_users', ['postclass_uid'], ['ua_user_id'])
    # op.create_foreign_key(None, 'res_postclasses', 'res_postclasses', ['postclass_pid'], ['postclass_id'])
    # op.create_foreign_key(None, 'res_posts', 'ua_users', ['author_id'], ['ua_user_id'])
    # op.create_foreign_key(None, 'res_posts', 'res_posts', ['post_pid'], ['post_id'])
    # op.create_foreign_key(None, 'res_posts', 'res_postclasses', ['post_cid'], ['postclass_id'])
    # op.create_foreign_key(None, 'ua_session_data', 'ua_session_base', ['ua_sb_key'], ['ua_sb_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'ua_session_data', type_='foreignkey')
    # op.drop_constraint(None, 'res_posts', type_='foreignkey')
    # op.drop_constraint(None, 'res_posts', type_='foreignkey')
    # op.drop_constraint(None, 'res_posts', type_='foreignkey')
    # op.drop_constraint(None, 'res_postclasses', type_='foreignkey')
    # op.drop_constraint(None, 'res_postclasses', type_='foreignkey')
    # op.alter_column('res_postclasses', 'postclass_uid', existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.drop_column('res_postclasses', 'postclass_pid')
    # op.drop_constraint(None, 'res_files', type_='foreignkey')
    # ### end Alembic commands ###
