"""add class, update post

Revision ID: a5e7ce8a9f24
Revises: e495fdaee93e
Create Date: 2018-10-13 16:09:43.003956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a5e7ce8a9f24'
down_revision = 'e495fdaee93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('res_postclasses',
    sa.Column('postclass_id', sa.Integer(), nullable=False),
    sa.Column('postclass_uid', sa.Integer(), nullable=False),
    sa.Column('postclass_name', sa.String(length=128), nullable=True),
    sa.Column('postclass_createtime', sa.DateTime(), nullable=True),
    #sa.ForeignKeyConstraint(['postclass_uid'], ['ua_users.ua_user_id'], ),
    sa.PrimaryKeyConstraint('postclass_id')
    )
    op.add_column('res_files', sa.Column('file_uid', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'res_files', 'ua_users', ['file_uid'], ['ua_user_id'])
    op.add_column('res_posts', sa.Column('post_cid', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'res_posts', 'res_postclasses', ['post_cid'], ['postclass_id'])
    op.alter_column('res_files', 'file_creattime', nullable=True, new_column_name='file_createtime', existing_type=sa.DateTime())
    op.alter_column('res_posts', 'post_creattime', nullable=True, new_column_name='post_createtime', existing_type=sa.DateTime())
    op.alter_column('ua_session_base', 'ua_sb_creattime', nullable=True, new_column_name='ua_sb_createtime', existing_type=sa.BigInteger())
    op.alter_column('ua_users', 'ua_creattime', nullable=True, new_column_name='ua_createtime', existing_type=sa.DateTime())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('res_files', 'file_createtime', nullable=True, new_column_name='file_creattime', existing_type=sa.DateTime())
    op.alter_column('res_posts', 'post_createtime', nullable=True, new_column_name='post_creattime', existing_type=sa.DateTime())
    op.alter_column('ua_session_base', 'ua_sb_createtime', nullable=True, new_column_name='ua_sb_creattime', existing_type=sa.BigInteger())
    op.alter_column('ua_users', 'ua_createtime', nullable=True, new_column_name='ua_creattime', existing_type=sa.DateTime())
    #op.drop_constraint(None, 'res_files', type_='foreignkey')
    #op.drop_constraint(None, 'res_posts', type_='foreignkey')
    op.drop_column('res_files', 'file_uid')
    op.drop_column('res_posts', 'post_cid')
    op.drop_table('res_postclasses')
    # ### end Alembic commands ###
